### PR TITLE
Migration to go-kong

### PR DESCRIPTION
**Pull request by tjrivera**
This is a draft PR that I'm opening up to get eyes on while it is in progress. 

This PR migrates this provider from using `kevholditch/gokong` to `hbagdi/go-kong`. There are some important differences to note.

* I moved the `containers/` folder included here over from gokong to retain the same `docker test` functionality as before.
* This shouldn't be merge before https://github.com/hbagdi/go-kong/pull/22 if we want to maintain the setting of `Type` on passive health checks.
* There's a bit of a difference between the way gokong handles 404s from Kong vs go-kong. go-kong will throw an error, so there's some checking here to handle that case and rely on nil items to determine the existence of a resource in Kong. 
* I've started to move away from creating go-kong structs via `createXxxFromResourceData` functions as go-kong relies on the resource ID being within the struct as opposed to gokong which expects it to be passed as a parameter to CRUD functions. I thought that creating structs from resource data _per operation_ might be a bit more explicit and clear going forward. This isn't reflected through the entirety of the PR but I'd like it to get there.
* I'm a bit confused by the `consumer_plugin_config` resource. I need to reason a little bit more about how this would differ from the normal plugin endpoints. Any feedback is helpful!

I have most of the acceptance tests passing here except for the consumer plugin config work, and some tests related to the passive health check type issue mentioned earlier. I'm still working on cleaning this up but wanted to get eyes on it sooner rather than later. 

Thanks,
Tyler

### CODE REVIEW

**Comment by tjrivera** [comment]
I spent some time hacking on this today and found that the `consumer_plugin_config` resource has some wrinkles that make the migration to go-kong a bit trickier. 

It seems that in the original implementation a JSON string is passed through to kong for a given consumer + plugin name and without any validation in the client. [The body is just blindly passed](https://github.com/kevholditch/gokong/blob/master/consumers.go#L153-L177)

Things work a bit differently in `go-kong` with each consumer plugin config being represented as their own service. i.e. for plugin name to go-kong `Service` we have 

* `jwt` -> `JWTAuths`
* `basic-auth` -> `BasicAuths`
* `oauth2` -> `Oauth2Credentials`

etc. 

This situation makes it difficult to maintain backwards compatibility to the current Terraform resource as it exists, as it's difficult to map JSON provided as a string in the resource to specific struct attributes in `go-kong`. 

I'm wondering if it makes more sense to deprecate the `consumer_plugin_config` resource in favor of creating specific resources for each auth type (to better map to go-kong).

**Comment by kevholditch** [comment]
@tjrivera i think in this case it makes sense to deprecate the old resource and create new ones for each. We can bump the major version number on the provider

**Comment by legal90** [comment]
Hi @tjrivera,
Thank you very much for this PR! It would be great to make this provider compatible with Kong Enterprise and rely on the recent library.

I went through the discussion in https://github.com/kevholditch/gokong/pull/74 and then found that the library `hbagdi/go-kong` has been promoted as the official one and currently is available as https://github.com/kong/go-kong.

@tjrivera , are you interested in updating this PR to the latest state of `kong/go-kong` instead?

P.s. I see that this terraform provider is not actively developed now, but I really hope that we can push it forward. And this PR is the most important point for that.
I noticed multiple forks around, so I hope that together with other community members we can bring it alive and maybe even officially supported as that happened with `kong/go-kong` (thank you, @hbagdi 👍 )

**Comment by kevholditch** [comment]
@legal90 @tjrivera thanks a lot for the effort put in here.  I'm sorry I've been off the grid for a while just haven't had the time to put into the provider to keep it running.

I'm happy to donate this provider over to the official Kong repo if you guys will be able to keep it maintained over there.  Think it would be good to finish updating the provider to work with the kong/gokong client as it is much more fully featured than my original client

**Comment by kevholditch** [comment]
thanks for your work on this, I have just finished off your work and the provider is now using the official go-kong client

**Pull request closed without merging**
