### PR TITLE
Adding support for 'enabled' field on plugins (#77)

### PR DESCRIPTION
**Pull request by charlie-retzler**
Added ability to toggle enabled / disabled on Kong Plugin (Issue #77) and supporting tests.

### CODE REVIEW

**Comment by charlie-retzler** [comment]
@kevholditch Thank you for the feedback. I had inadvertently missed these changes you suggested. I submitted a MR https://github.com/kevholditch/gokong/pull/40 on gokong with the changes. I also updated this MR with your suggestions assuming the other MR is merged first.

**Comment by kevholditch** [comment]
@charlie-retzler thanks, this has now been merged into gokong

**Comment by charlie-retzler** [comment]
Thanks @kevholditch. The MR has the updated code incorporated from gokong merge. Do you require any additional changes on this?

**Comment by kevholditch** [comment]
@charlie-retzler thanks for your work on this

**Comment by kevholditch** [comment]
released in `v4.5.1`

**Pull request merged**
